---
layout: cv
title: Makayla Hansen's CV
---


makaylahansen04@gmail.com • (435) 237-3530 • [linkedin.com/in/makaylahansen2023](https://www.linkedin.com/in/makaylahansen2023)

---

## Education

#### Brigham Young University - Idaho
September 2023 - Present

Bachelor of Science; Software Engineering — 3.97 GPA

- Emphasis in Full-Stack Web Development
- Certificates:
  - IT Fundamentals (Awarded December 2025)
  - Web and Computer Programming (Awarded April 2026)
  - Data Science (Current)

<br>

#### Box Elder High School
August 2019 - June 2023

High School Diploma — 4.0 GPA

- Top 3%

---

## Work Experience

#### BYU-Idaho — Curriculum Specialist
Rexburg, ID | June 2026 - Present

- Worked closely with Curriculum Analyst to improve degree programs across the University
- Used organizational skills to set up a brand-new team
- Leveraged AI tools to improve daily tasks and overall performance of manual tasks

<br>

#### BYU-Idaho — Degree Verification Specialist
Rexburg, ID | September 2025 - June 2026

- Partnered with a team to guarantee integrity of over 200,000 student records through business systems analysis, reporting, and workflow improvement
- Led a project overseeing verification of over 10,000 applications
- Leveraged technological skills to develop 2 mail merge converters, organize data, monitor graduation activity, support audits, and identify process improvement
- Sought enhancements to improve efficiency, data integrity, and student experience, helping about 5,000 students graduate

<br>

#### BYU-Pathway Worldwide — Enrollment Verification Team
Remote | June 2025 - September 2025

- Collaborated with a team to manually enter student data, handling sensitive information and maintaining data integrity. Completed over 150 cases

<br>

#### BYU-Idaho — Copyeditor for Online Content
Rexburg, ID | April 2024 - September 2024

- Collaborated with a team to edit approximately 40 textbook chapters and 15 Canvas courses for BYU-Idaho and BYU Pathway Worldwide. Checked for copyright and cultural infringement and followed guidelines set by the company style guide

---

## Projects

#### Motor Sport Driver Stats
January 2026 - April 2026

- Built a website using HTML, CSS, JavaScript, and JSON
- Created over 20 API calls with strong interactivity between user and program

<br>

#### Calendar Application
January 2026 - Present

- Created a calendar application with a team

---

## Leadership

#### Future Business Leaders of America — Vice President
Brigham City, UT | August 2022 - June 2023

- Guided over 15 club activities to improve academics and prepare for state and national competitions

<br>

#### Key Club — President
Brigham City, UT | August 2020 - June 2022

- Led a team of 6 members to serve school and community when needs arose


## Copyright 2026